### ISSUE TITLE
I should be able to configure the name of the column

### ISSUE THREAD

**Issue by koombea-railscasts** [dfurber/ar_doc_store#1]
Hi, this gem looks really cool and currently I'm using jsonb in a production app and I would like to use this gem but can I configure the name of the column to be something different to "data". I'm currently using "metadata" as my column and since is in production already I don't want to touch that column name.

**Comment by jaredcwhite** [comment]
Ditto on this - I'm looking at using this for a new project but want to use "metadata" and not "data" as the column name. Anyway, looks like a super cool gem!

**Comment by dfurber** [comment]
So sorry I didn't see this issue until just now. I'm thinking something like "self.data_column = 'metadata'" a la self.table_name=. How does that sound?

**Comment by dfurber** [comment]
I just added self.json_column = :json_column_name support. Sorry about the delay!
