### ISSUE TITLE
Doesn't validate, just casts?

### ISSUE THREAD

**Issue by swrobel** [dfurber/ar_doc_store#5]
I'm a bit confused about the purpose of this gem, I suppose. I thought that the data types were for validation, however it seems that they simply cast, resulting in odd behavior.

```ruby
class Building < ActiveRecord::Base
  include ArDocStore::Model

  json_attribute :storeys, :integer
end

>> b = Building.create(storeys: 10)
...
>> b.storeys
=> 10
>> b.storeys = 'test'
>> b.storeys
=> 0
```

**Comment by dfurber** [comment]
The JSON attribute's behavior is similar to an ActiveRecord column in that respect. You supply your own validation. The column/attribute handles casting to correct data type.

**Comment by swrobel** [comment]
Thanks for the quick reply! I was just checking out [storext](https://github.com/G5/storext) and it behaves the same way, so I guess maybe I was expecting too much baked into these libs.

**Comment by swrobel** [comment]
Actually, it turns out this is more problematic than I'd thought. The typecasting occurs before validations are run, so if I add `validates :storeys, numericality: { integer: true }` it still passes since storeys is cast from 'test' to 0 before it validates.

**Comment by swrobel** [comment]
FYI, switched to [jsonb_accessor](https://github.com/devmynd/jsonb_accessor) which plays nicely with validations in all of my tests.
